### ISSUE TITLE
GetBalance does not  work

### ISSUE THREAD

**Issue by SergeevGregory** [mscheetz/KuCoinApi.NetCore#1]
Dear Developer,
I tried to use private (trade) Kucoin API, and have trouble.
When I try to get Balances, I got exception in GetApiStream in OnGetBalances:

_Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'KuCoinApi.NetCore.Entities.Balance[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'data.total', line 1, position 99._

Hope you can help. Thx.

**Comment by mscheetz** [comment]
I'll jump on it tonight and get it fixed. Thanks for reporting this issue!

**Comment by SergeevGregory** [comment]
Can you also test PostTrade?

**Comment by mscheetz** [comment]
Yessir

**Comment by mscheetz** [comment]
Both are fixed in latest NuGet release: https://www.nuget.org/packages/KuCoinApi.NetCore/1.5.3
