### ISSUE TITLE
C#

### ISSUE THREAD

**Issue by diogoribeirodev** [mscheetz/KuCoinApi.NetCore#19]
Hi, i was wondering if am i able to use this code in a Windows Form Application(.NET Framework)?I am trying to build an application where the user can do everything he would do in the kucoin website/app! I am finding a hard time using the code.

**Comment by mscheetz** [comment]
Yes, feel free to use it's it written in .net standard so it would work with any flavor of .net.

**Comment by diogoribeirodev** [comment]
But when i type the function on a C# class, he doesn't recognize her!

**Comment by mscheetz** [comment]
Did you follow the readme? You should just install the nuget package to the project you want to access it, then just call it.

**Comment by diogoribeirodev** [comment]
i did, but when i try to call it, i get an error saying it doesnt exist

Scheetz ***@***.***> escreveu no dia sexta, 9/04/2021 à(s)
01:19:

**Comment by diogoribeirodev** [comment]
I get this error when trying to iniciate:
Severity Code Description Project File Line Suppression State
Error CS0246 The type or namespace name 'IKuCoinDotNet' could not be found
(are you missing a using directive or an assembly reference?) Kucoin
C:\Users\ribei\Downloads\Kucoin\Kucoin.cs 30 Active

Diogo Ribeiro ***@***.***> escreveu no dia sexta, 9/04/2021
à(s) 11:26:

**Comment by mscheetz** [comment]
I'll take a look in a couple hours. What version of .net is your app?

**Comment by diogoribeirodev** [comment]
[image: image.png]

Scheetz ***@***.***> escreveu no dia sexta, 9/04/2021 à(s)
12:00:

**Comment by diogoribeirodev** [comment]
[image: image.png]

Diogo Ribeiro ***@***.***> escreveu no dia sexta, 9/04/2021
à(s) 12:04:

**Comment by diogoribeirodev** [comment]
Do you know what's the problem?

A sexta, 9/04/2021, 12:08, Diogo Ribeiro ***@***.***>
escreveu:

**Comment by mscheetz** [comment]
I created a new Windows form project, .net framework 4.7.2.

Added the nuget package and called it up in the program.cs.

Here's a video of it: https://www.youtube.com/watch?v=tn4k0RkdI3Q

**Comment by diogoribeirodev** [comment]
Thank you!

A sábado, 10/04/2021, 16:43, Scheetz ***@***.***> escreveu:

**Comment by mscheetz** [comment]
Did you get it working?

**Comment by diogoribeirodev** [comment]
If i delete "await" the error disappears.

A sábado, 10/04/2021, 17:34, Diogo Ribeiro ***@***.***>
escreveu:

**Comment by diogoribeirodev** [comment]
i get his error when using var balances = await kucoin.GetBalances();

Severity Code Description Project File Line Suppression State
Error CS4033 The 'await' operator can only be used within an async method.
Consider marking this method with the 'async' modifier and changing its
return type to 'Task'. Trading Bot C:\Users\ribei\Downloads\Trading
Bot\API.cs 17 Active

but if i delete the "away" the error dissapears.

A sábado, 10/04/2021, 17:34, Diogo Ribeiro ***@***.***>
escreveu:

**Comment by mscheetz** [comment]
All endpoints are async. You can run async from a sync method:
`
    static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            Task.Run(() => MainAsync());
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new Form1());
        }

        static async void MainAsync()
        {
            var kucoin = new KuCoinDotNet();

            var pair = "BTC-USDT";
            var ticker = await kucoin.GetTicker(pair);
        }
    }
`

**Comment by diogoribeirodev** [comment]
Thank you! One more question is this how you show the balances? because it
doesnt show the balances but "Colecção" wich means Colection
Note: the market_order function is working!!!!!!
[image: image.png]

Scheetz ***@***.***> escreveu no dia sábado, 10/04/2021 à(s)
18:59:
