### ISSUE TITLE
PostTrade doesn't work

### ISSUE THREAD

**Issue by SergeevGregory** [mscheetz/KuCoinApi.NetCore#2]
Dear Developer, today I tested new version of Package. GetBalance issue was fixed, but PostTrade doesn't work... I attached screen with error. Hope you will fix this issue too. Thx

![posttrade](https://user-images.githubusercontent.com/24494272/48624334-2db92800-e9bd-11e8-963e-26919b78f9cb.png)

**Comment by SergeevGregory** [comment]
I found that problem is in strings in public async Task<ApiResponse<Dictionary<string, string>>> PostTrade:

`
            var queryString = new List<string>
            {
                $"amount={tradeParams.quantity}",
                $"price={tradeParams.price}",
                $"symbol={kuPair}",
                $"type={tradeParams.side}"
            };
`
Because in Russian Culture default decimal separator is ",", not ".".
Possible fix is:
`
            var queryString = new List<string>
            {
                $"amount={tradeParams.quantity}".Replace(",","."),
                $"price={tradeParams.price}".Replace(",","."),
                $"symbol={kuPair}",
                $"type={tradeParams.side}"
            };
`
I think in next release you have to fix this issue in all places where you convert decimal to string.

**Comment by mscheetz** [comment]
Will look into it tonight. Thanks for the possible fix too.

There is a LimitOrder endpoint you can try as well.

**Comment by mscheetz** [comment]
Fixed in latest
