### ISSUE TITLE
C# Console

### ISSUE THREAD

**Issue by diogoribeirodev** [mscheetz/KuCoinApi.NetCore#20]
Hi, i have an issue. I am trying to run the following code on a command promt/console but i keep getting this error
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS5001	Program does not contain a static 'Main' method suitable for an entry point	KCSBOTBROS	C:\Users\ribei\OneDrive\Ambiente de Trabalho\KCSBOTBROS\CSC	1	Active

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Threading;
using KuCoinApi.Net;

namespace KCSBOTBROS
{
    public class Program
    {
        static async void Main(string[] args)
        {
            Console.Title = "KCSBotBros";
            IKuCoinDotNet kucoin = new KuCoinDotNet("1", "1", "1");
            Console.ForegroundColor = ConsoleColor.White;
            Console.Write("Input the asset you want to invest with:");
            string asset = Console.ReadLine();
            Console.Write("Input the amount you want to invest:");
            string amount = Console.ReadLine();
            Console.Write("Input the desired profit(%):");
            string profit = Console.ReadLine();
            Console.Write("Input symbol:");
            string symbol = Console.ReadLine();
            string pair = symbol + "-" + asset;
            decimal price;
            var market_order = await kucoin.PlaceMarketOrder(pair, KuCoinApi.Net.Entities.Side.BUY, 1);
            var orderdetails = await kucoin.GetOrder(market_order);
            price = orderdetails.DealFunds / orderdetails.DealSize;
            Console.WriteLine("Deal Funds:" + orderdetails.DealFunds + "\n" + "Deal Size:" + orderdetails.DealSize + "\n" + "Deal Price:" + price);
        }        
    }
}

**Comment by mscheetz** [comment]
Change your Main() return type from `void` to `Task`
`
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Threading;
using KuCoinApi.Net;

namespace KCSBOTBROS
{
public class Program
{
static async Task Main(string[] args)
{
Console.Title = "KCSBotBros";
IKuCoinDotNet kucoin = new KuCoinDotNet("1", "1", "1");
Console.ForegroundColor = ConsoleColor.White;
Console.Write("Input the asset you want to invest with:");
string asset = Console.ReadLine();
Console.Write("Input the amount you want to invest:");
string amount = Console.ReadLine();
Console.Write("Input the desired profit(%):");
string profit = Console.ReadLine();
Console.Write("Input symbol:");
string symbol = Console.ReadLine();
string pair = symbol + "-" + asset;
decimal price;
var market_order = await kucoin.PlaceMarketOrder(pair, KuCoinApi.Net.Entities.Side.BUY, 1);
var orderdetails = await kucoin.GetOrder(market_order);
price = orderdetails.DealFunds / orderdetails.DealSize;
Console.WriteLine("Deal Funds:" + orderdetails.DealFunds + "\n" + "Deal Size:" + orderdetails.DealSize + "\n" + "Deal Price:" + price);
}
}
}
`

**Comment by diogoribeirodev** [comment]
I changed and now i get this error
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'Task' could not be found (are you missing a using directive or an assembly reference?)	KCSBOTBROS	C:\Users\ribei\OneDrive\Ambiente de Trabalho\KCSBOTBROS\Program.cs	14	Active

**Comment by Diogovski** [comment]
It's working now, i forgot to add using System.Threading.Tasks;
Thx for the help.
Also is it possible to use funds on the market order function instead of size?

**Comment by Diogovski** [comment]
?

**Comment by Diogovski** [comment]
?

**Comment by diogoribeirodev** [comment]
It's working now, i forgot to add using System.Threading.Tasks;
Thx for the help.
Also is it possible to use funds on the market order function instead of size?

**Comment by mscheetz** [comment]
Check the MarketOrderParams object

**Comment by diogoribeirodev** [comment]
It doesn't let me edit, it's locked! How can i change it and what i write?

A terça, 13/04/2021, 21:17, Scheetz ***@***.***> escreveu:

**Comment by diogoribeirodev** [comment]
?

A terça, 13/04/2021, 21:37, Diogo Ribeiro ***@***.***>
escreveu:

**Comment by mscheetz** [comment]
`var marketOrderParams = new KuCoinApi.Net.Entities.MarketOrderParams()`
`{`
                `Funds = 1000,`
                `Pair = "BTC-USDT"`
           ` };`

`            var trade = await kucoin.PlaceMarketOrder(marketOrderParams);`

**Comment by MoneyMachine555** [comment]
I get an error saying Input string was not in a correct format.

A quarta, 14/04/2021, 00:09, Scheetz ***@***.***> escreveu:

**Comment by diogoribeirodev** [comment]
I get an error saying Input string was not in a correct format.

**Comment by diogoribeirodev** [comment]
?

**Comment by mscheetz** [comment]
Check out this unit test: https://github.com/mscheetz/KuCoinApi.Net/blob/869334ac02446c30fe05a6e61115f0b48ee9bc98/KuCoinApi.Net/KuCoinApi.Net.Tests/Tests/KuCoinRepositoryTests.cs#L177

**Comment by diogoribeirodev** [comment]
i get this error System.NullReferenceException: 'Object reference not set to an instance of an object.' on the line 
var trade = await kucoin.PlaceMarketOrder(marketorder);

the code:
var marketorder = new KuCoinApi.Net.Entities.MarketOrderParams
            {
                Pair = pair,
                Side = KuCoinApi.Net.Entities.Side.BUY,
                Funds = Convert.ToDecimal(amount)
            };
            var trade = await kucoin.PlaceMarketOrder(marketorder);
