### ISSUE TITLE
Please, add List dealt orders(merged) ( /v1/order/dealt)

### ISSUE THREAD

**Issue by SergeevGregory** [mscheetz/KuCoinApi.NetCore#3]
Dear developer,
I need function "List dealt orders(merged)" from kucoin api documentation, but your Lib hasn't it (May be I mistake?). Can you add it? It is important, that symbol field can be empty, in this case all user history returned by server. Hope you will have time to add this functionality to your library. Thx.

**Comment by mscheetz** [comment]
Oh, wow, I completely missed that endpoint. Will add it.

**Comment by mscheetz** [comment]
Added in latest
