### ISSUE TITLE
use full coin pair name

### ISSUE THREAD

**Issue by h0wXD** [mscheetz/KuCoinApi.NetCore#4]
Helper.CreateDashedPair uses substring of 3's, except not all coins have a length of 3

I haven't run the program nor tests, but I don't think this is correct.

e.g. TOMO-BTC
would make https://api.kucoin.com/v1/open/chart/history?symbol=TOM-BTC
and throw `SYMBOL NOT FOUND`
instead of https://api.kucoin.com/v1/open/chart/history?symbol=TOMO-BTC

Suggest you lazy load coins in some dictionary to map them symbol <-> kuPair

**Comment by mscheetz** [comment]
I'll take a look at it later today.

**Comment by mscheetz** [comment]
Ok just fixed and updated the nuget package too.

Thanks for the feedback. Happy trading!
