### ISSUE TITLE
Please, add List of all user's orders

### ISSUE THREAD

**Issue by SergeevGregory** [mscheetz/KuCoinApi.NetCore#5]
Dear developers,
I found that request "https://api.kucoin.com/v1/order/active-map?symbol=" returns all open user's orders. Can you add this feature to your sdk?

Thanks :)

**Comment by mscheetz** [comment]
added GetOpenOrdersDetailAsync(symbol) and GetOpenOrdersDetail(symbol). also updated nuget

**Comment by mscheetz** [comment]
I didn't realize that was a valid call. I'll look into it today or tomorrow.

Documentation says symbol is required: https://kucoinapidocs.docs.apiary.io/#reference/0/trading/list-active-orders-in-kv-format

**Comment by SergeevGregory** [comment]
But it works with empty symbol: https://github.com/sammchardy/python-kucoin/issues/1

**Comment by mscheetz** [comment]
Ok, found it, I've added new api: GetOpenOrdersDetailAsync() and GetOpenOrdersDetail()

Both are empty and take no parameter. NuGet updated as well.
